#!/bin/bash
gcc -g -O -c ../0x08-recursion/_putchar.c
gcc -g -O -c ../0x02-functions_nested_loops/3-islower.c
gcc -g -O -c ../0x02-functions_nested_loops/4-isalpha.c
gcc -g -O -c ../0x02-functions_nested_loops/6-abs.c
gcc -g -O -c ../0x04-more_functions_nested_loops/0-isupper.c
gcc -g -O -c ../0x04-more_functions_nested_loops/1-isdigit.c
gcc -g -O -c ../0x05-pointers_arrays_strings/2-strlen.c
gcc -g -O -c ../0x05-pointers_arrays_strings/3-puts.c
gcc -g -O -c ../0x05-pointers_arrays_strings/9-strcpy.c
gcc -g -O -c ../0x05-pointers_arrays_strings/100-atoi.c
gcc -g -O -c ../0x06-pointers_arrays_strings/0-strcat.c
gcc -g -O -c ../0x06-pointers_arrays_strings/1-strncat.c
gcc -g -O -c ../0x06-pointers_arrays_strings/2-strncpy.c
gcc -g -O -c ../0x06-pointers_arrays_strings/3-strcmp.c
gcc -g -O -c ../0x07-pointers_arrays_strings/0-memset.c
gcc -g -O -c ../0x07-pointers_arrays_strings/1-memcpy.c
gcc -g -O -c ../0x07-pointers_arrays_strings/2-strchr.c
gcc -g -O -c ../0x07-pointers_arrays_strings/3-strspn.c
gcc -g -O -c ../0x07-pointers_arrays_strings/4-strpbrk.c
gcc -g -O -c ../0x07-pointers_arrays_strings/5-strstr.c
